export const CATEGORIES_A = [
  'e-commerce product list',
  'e-commerce product details',
  'e-commerce cart',
  'about company',
  'frequently asked questions',
  'press',
  'legal privacy policy',
  'legal terms and conditions',
  'accessibility statement',
  'e-commerce returns and exchanges',
  'e-commerce assistance',
  'blog',
  'account register',
  'account login',
  'my account',
  'account orders',
  'physical store location',
  'contact us',
  'e-commerce promotional content',
  'other',
];

export const CATEGORIES_B = [
  'e-commerce product list',
  'e-commerce product details',
  'e-commerce cart',
  'e-commerce returns/refunds and exchanges',
  'e-commerce shipping/delivery information',
  'e-commerce customer reviews/testimonial',
  'e-commerce gift cards',
  'customer assistance/support or contact us',
  'information about the company',
  'career opportunities',
  'blog',
  'physical store address/location/direction',
  'press material',
  'legal privacy policy',
  'legal terms and conditions',
  'legal accessibility statement',
  'my account',
  'account register',
  'account login',
  'account orders',
  'page not found',
  'other',
];

export const CATEGORIES_C = [
  'e-commerce products list',
  'e-commerce product details',
  'e-commerce cart',
  'e-commerce returns/refunds and exchanges',
  'e-commerce shipping/delivery information',
  'e-commerce customer reviews/testimonial',
  'e-commerce gift cards',
  'customer service/assistance/support',
  'contact us/get a quote',
  'information about the company',
  'career opportunities',
  'blog',
  'physical store address/location/direction',
  'press material',
  'legal informations',
  'account login/register',
  'account orders',
  'page not found',
  'other',
];
